const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "+254734033959"
const SESSION_ID = "PRABATH-MD~aOojQa5R#tY8DuzyqfrJ7azgHkieNmS9Z-PWfkeLwNKAEQtkJjJM"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
